title: Machine Learning Course
description: Starting from Data Science offers examples (with Python code) and explanation (in Twitter threads) on concepts and techniques of Machine Learning, Deep Learning and NLP
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
