title: Machine Learning Course
description: Starting from Data Science, examples (with code) and explanation of Machine Learning, Deep Learning and NLP techniques
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
